[dashboards]
# Allow refresh intervals down to 500ms for real-time panels
min_refresh_interval = 500ms

[auth.anonymous]
enabled = true
org_role = Viewer

[plugins]
allow_loading_unsigned_plugins = hadesarchitect-cassandra-datasource
